import type { Metadata } from "next";
import "../sass/index.scss";

import CTA from "@/components/CTA";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Scoot Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          {children}
          <CTA />
        </main>
        <Footer />
      </body>
    </html>
  );
}
